all: 

	g++ ./Source/firstStep.cpp -o firstStep
	g++ ./Source/firstStep_out.cpp -o firstStep_out
	g++ ./Source/SecondStep.cpp -o secondStep
	g++ ./Source/SecondStep_out.cpp -o secondStep_out
	g++ ./Source/opti.cpp -o opti
